name = "maf-machine-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "MAF_TOKENS"
id = "PLACEHOLDER"
preview_id = "PLACEHOLDER"

[[kv_namespaces]]
binding = "MAF_ACTIVITIES"
id = "PLACEHOLDER"
preview_id = "PLACEHOLDER"

[[kv_namespaces]]
binding = "MAF_SETTINGS"
id = "PLACEHOLDER"
preview_id = "PLACEHOLDER"
